language: php

php:
  - 5.6
  - 7.0
  - 7.3

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'

    - php: 7.1
      env: DB=sqlite db_dsn='sqlite:///:memory:'

    - php: 5.6
      env: PREFER_LOWEST=1

    - php: 7.2
      env: CHECKS=1 DEFAULT=0

    - php: 7.2
      env: CODECOVERAGE=1 DEFAULT=0

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable ; fi

  - if [[ $DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE cakephp_test;' ; fi
  - if [[ $DB == 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres ; fi

script:
  - vendor/bin/phpunit;

notifications:
  email: false